PROGRAM SURFACE_DU_CREE;
CONST PI= 3.14;
VAR R,S,P : REAL;
BEGIN
WRITELN('DONNER_LE_RAYON');
READLN(R);
S:= PI*SQR(R);
P:= 2*PI*R;
WRITELN('LA_SURFACE_EST ',S:5:2);
WRITELN('LE_PERIMETRE_EST ',P:5:2);
READLN(S,P);
END.